services:
  db:
    image: postgres:alpine
    container_name: 2eden_db
    restart: always
    env_file:
      - ./.env
    command: -c max_connections=100 -c shared_buffers=2000MB
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PSW}
      POSTGRES_DB: ${PSQL_DB}
      TZ: Europe/Moscow
    ports:
      - 1100:5432
    networks:
      - 2eden_network
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:alpine
    container_name: advance_report_cache
    restart: always
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 1000:6379
    networks:
      - 2eden_network
    volumes:
      - cache_data:/data
  app:
    build: .
    container_name: 2eden_api
    restart: always
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
      - cache
    ports:
      - 3000:8000
    networks:
      - 2eden_network

networks:
  2eden_network:

volumes:
  db_data:
  cache_data: