version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/root/.project
    command: sh -c 'echo $PG_CONFIG && python main.py'

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=2eden_admin
      - POSTGRES_PASSWORD=Ae8yTgZFxRpvmE1XeoVIOz5Ha6Ye63
      - POSTGRES_DB=2eden_db

  redis:
    image: redis:6
    command: redis-server --requirepass irjiPeQAPf1lL6ukoCm0LPnvpP4P0A
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: